replicaCount: 2

image:
  repository: ghcr.io/hannahhh26/health-check-api
  tag: "sha-4ae6af43bd6d88b6a7b296010fa98733a209530d"
  pullPolicy: IfNotPresent

service:
  port: 8000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

config:
  appEnv: kubernetes-local

existingSecret: health-check-api-practice